name: Deploy Frontend to VPS
on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Fijamos Yarn 1 (classic)
      - name: Use Yarn 1.x (classic)
        run: |
          corepack enable
          corepack prepare yarn@1.22.19 --activate
          yarn -v

      - name: Build React
        working-directory: frontend
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Upload build to VPS
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: frontend/build/
          remote_path: /var/www/metalmade.store/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            nginx -t && systemctl reload nginx
